routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');
Route::resource('licencia_equipo','LicenciaEquipoController');
Route::get('licencia_equipo/create','LicenciaEquipoController@create')->name('licencia_equipo.create');
Route::get('licencia_equipo/numero/{id}','LicenciaEquipoController@numero')->name('licencia_equipo.numero');
Route::get('equipo/numero/{id}','EquipoController@numero')->name('equipo.numero');
 Route::resource('equipo','EquipoController');
 Route::get('equipo/create','EquipoController@create')->name('equipo.create');
 Route::get('equipo/show/{id}','EquipoController@show')->name('equipo.show');
Route::post('equipo/store/{id}','EquipoController@store')->name('equipo.store');
Route::get('index', function () {
    return redirect('equipo');
 });
 Route::get('licencia_equipo/show/{id}','LicenciaEquipoController@show')->name('licencia_equipo.show');
 Route::post('licencia_equipo/store/{id}','LicenciaEquipoController@store')->name('licencia_equipo.store');
 Route::get('csv', function(){
    $n= DB::table('equipo_licencia')
    ->select('licencias.nombre_programa','licencias.digitos','licencias.version','licencias.subversion','equipos.nserie_equipo','users.name','users.departamento')
     ->join('licencias','equipo_licencia.licencia_id','=','licencias.id')
     ->join('equipos','equipo_licencia.equipo_id','=','equipos.id')
     ->join('users','equipos.user_id','=','users.id')
     ->get();
     $filename = "licencias.csv";
     $handle = fopen($filename, 'w+');
     fputcsv($handle, array('nombre del programa', 'digitos','version','subversion','numero de serie del equipo','usuario','departamento'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->nombre_programa,$row->digitos,$row->version,$row->subversion,$row->nserie_equipo,$row->name,$row->departamento));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'licencias.csv', $headers);

 })->name('exportar');
 
//rutas para solicitud de mantenimiento
Route::resource('mantenimiento','MantenimientoController');
Route::get('mantenimiento/pdf/{id}','MantenimientoController@create_pdf')->name('mantenimiento.pdf');

//rutas para apoyo de correos
Route::resource('apoyo','ApoyoController');
Route::get('/refresh_captcha', 'ApoyoController@refreshCaptcha')->name('refresh');
Route::resource('correos','CorreoController');
Route::get('correos/destroy/{id}', 'CorreoController@destroy')->name('correos.destroy');
Route::get('correos/show/{id}', 'CorreoController@show')->name('correos.show');
Route::get('csvc', function(){
    $n= DB::table('apoyos')
    ->select('*')
    ->from('apoyos')
     ->get();
    
   $filename = "ApoyoCorreosCompleto.csv";
   $handle = fopen($filename, 'w+');
     fputcsv($handle, array('numero de control', 'carrera','apellido paterno','apellido materno','nombre','peticion','descripcion del problema'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->numerocontrol,$row->carrera,$row->apellidoPaterno,$row->apellidoMaterno,$row->nombre,$row->opcion,$row->descripcion));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'ApoyoCorreosCompleto.csv', $headers);

 })->name('exportarcompleta');



Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

resources/views/asignacioneditar.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                         @yield('bread-licenciasconsulta')
                        
                        @yield('solicitudes-tabla')
                        @yield('content')
                        @yield('modaleditar')
                        @yield('modalregistro')
                    </div>
                    {{-- @yield('footer') --}}
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/categoria.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')


<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('bread-categorias')
                        @yield('categoria-tabla')
                        @yield('modaleliminar')
                    </div>
                    @yield('footer')
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/esperaAprob.blade.php
@include('layouts.app')
@extends('registro')

@section('registro')
<div class="container" style="margin-top:2px;">
  <div class="card card-register mx-auto " >
    <div class="card-header"> Apoyo Correo Electrónico </div>
    <div class="card-body">
  <div class="card-header" style=" text-align: center ;">
           
            !!!Solicitud Generada Exitosamente!!!
        </div>
           
             <div class="card-body">
            <div class="table-responsive">
                Estamos verificando tu informacion
                 <p width="370" >Numero de atención: {{$generateOrder_nr}} </p> 
            </div>
        </div>
     </div>
 </div>
  </div>
       

  
@endsection

resources/views/formularioapoyo.blade.php
@include('layouts.app')
@extends('registro')

@section('registro')
<div class="container" style="margin-top:2px;">
  <div class="card card-register mx-auto " >
    <div class="card-header"> Apoyo Correo Electrónico </div>
    <div class="card-body">
    {{-- Validacion Mensajes --}}
    @if (count($errors) > 0)
    <div class="alert alert-danger">
    	<p>Corrige los siguientes errores:</p>
        <ul>
            @foreach ($errors->all() as $message)
                <li>{{ $message }}</li>
            @endforeach
        </ul>
    </div>
@endif
        <form method="POST" class="form-horizontal" enctype="multipart/form-data" action="{{route('apoyo.store')}}">
        @csrf
          <div class="form-group">
          <div class="form-row">
            <div class="col-md-6">
              <div class="form-label-group">
                <input type="text" id="numerocontrol" class="form-control" placeholder="Numero de control" required="required" name="numerocontrol">
                <label for="numerocontrol"> Número de control</label>
              </div>
            </div>
            
           <div class="col-md-6">
              <div class="form-label-group">
                <input type="text" id="carrera" class="form-control" placeholder="Carrera" required="required" name="carrera">
                <label for="carrera"> Carrera</label>
              </div>
            </div>
          
          </div>
        </div> 
     

         {{-- <div class="form-group">
          <div class="form-label-group">
            <input type="text" id="nombre" class="form-control" placeholder="Nombre" required="required" name="nombre">
            <label for="nombre">Nombre</label>
          </div>
        </div> --}}
         <div class="form-group">
          <div class="form-row">
            <div class="col-md-6">
          
              <div class="form-label-group">
                 
                <input type="text" id="apellidoPaterno" class="form-control" placeholder="Apellido Paterno" required="required" name="apellidoPaterno">
                <label for="apellidoPaterno"> Apellido Paterno </label>
              </div>
            </div>
            <div class="col-md-6">
             
              <div class="form-label-group">
             
                <input type="text" id="apellidoMaterno" class="form-control" placeholder="Apellido Materno" required="required" name="apellidoMaterno">
               <label for="apellidoMaterno"> Apellido Materno</label>
              </div>
            </div>
          </div>
        </div>
 <div class="form-group">
          <div class="form-label-group">
            <input type="text" id="nombre" class="form-control" placeholder="Nombre" required="required" name="nombre">
            <label for="nombre">Nombre(s)</label>
          </div>
        </div>
              <div class="form-group">
                        <div class="form-label-group">
                          <div class="form-group">
                  <select class="form-control" id="opcion" name="opcion"  required>
                    <option value="Correo Nuevo">Correo Nuevo</option>
                    <option value="Falla con el Correo">Falla con el Correo</option>
                    <option value="Restablecer Contraseña">Restablecer Contraseña</option>
                  </select>
                   
                </div>
          </div>
        </div>

 <div class="form-group">
    {{-- <label for="descripcion">Descripción del Problema</label> --}}
          <div class="form-label-group">
            <textarea type="text" class="form-control" id="descripcion" placeholder="Descripción del problema" name="descripcion" required="" ></textarea>
         {{-- <label for="descripcion">Descripción del Problema</label> --}}
          </div>
        </div>
        <div class="form-label-group">
          <input type="email" id="email" class="form-control" placeholder="Ej.: usuario@servidor.com" required="required" name="email">
          <label for="email"> Email de Contacto, Ej.: usuario@servidor.com</label>
        </div>
        
<div class="form-group">

          <div class="form-label-group">
          <label for="file">Subir foto de credencial:(Tipos de archivo permitidos: JPG,JPEG,PNG)</label>
          <br>
                <input type="file" name="foto" id="foto" >
               
          </div>
        </div>
{{-- Captcha --}}
         <div class="form-group{{ $errors->has('captcha') ? ' has-error' : '' }}">

                      {{-- <label for="captcha" class="col-md-4 control-label">Captcha</label> --}}


                      <div class="col-md-6">

                          <div class="captcha">

                          <span>{!! captcha_img('flat') !!}</span>

                           <button type="button" class="btn btn-success btn-refresh">Refresh</button>

                          </div>

                          <input id="captcha" type="text" class="form-control mt-2 " placeholder="Enter Captcha" name="captcha">


                          @if ($errors->has('captcha'))

                              <span class="help-block">

                                  <strong>{{ $errors->first('captcha') }}</strong>

                              </span>

                          @endif

                      </div>

                  </div>
        
        {{-- <button type="submit" class="btn btn-primary btn-block">
          {{ __('Register') }}
        </button> --}}
         <button type="submit" class="btn btn-primary btn-block"> Enviar</button>
      </form>
     
    </div>
  </div>
</div>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    $('.btn-refresh').click(function(){
        $.ajax({
            type:'GET',
            url: '{{ url('/refresh_captcha') }}',
            success: function(data){
                    $('.captcha span').html(data);
            }
        });
    });
    </script>

  

@endsection

resources/views/licenciasasignacion.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')
          
<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
           
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                         @yield('bread-licenciasasig')
                        {{-- <button class="btn btn-info" data-toggle="modal" data-target="#modalregistro" style="width: 200px; margin-left: 40%;"> Nueva asignación </button><br>  --}}
                        @yield('solicitudes-tabla')
                        @yield('content')
                        @yield('modaleditar')
                        @yield('modalregistro')
                    </div>
                    {{-- @yield('footer') --}}
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/licenciass.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                         @yield('bread-licencias')
                        <button class="btn btn-info" data-toggle="modal" data-target="#modalregistro" style="width: 200px; margin-left: 40%;"> Nueva licencia </button><br>
                        @yield('solicitudes-tabla')
                        @yield('content')
                        @yield('modaleditar')
                        @yield('modalregistro')
                    </div>
                    {{-- @yield('footer') --}}
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/login.blade.php
@include('layouts.scripts')
@include('layouts.footer')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body class="bg-dark">
            @yield('login')
        </body>
    </html>
    @yield('scripts')

resources/views/mantenimiento.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                         @yield('bread-mantenimiento')
                        <button class="btn btn-info" data-toggle="modal" data-target="#modalregistro" style="width: 200px; margin-left: 40%;"> Nueva Solicitud </button><br>
                        @yield('solicitudes-tabla')
                        @yield('content')
                        @yield('modaleditar')
                        @yield('modalregistro')
                    </div>
                    {{-- @yield('footer') --}}
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/pdf.blade.php
@include('layouts.scripts')
<!DOCTYPE html>
    <html lang="en">
        <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        </head>
        <body id="page-top">
            {{-- CONTENT --}}
            <div id="wrapper">
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('tabla')
                    </div>
                </div>
            </div>
        </body>
    </html>

resources/views/perfil.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('bread-perfil')
                        @yield('perfil')
                    </div>
                    @yield('footer')
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/registro.blade.php
@include('layouts.scripts')
@include('layouts.footer')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body class="bg-dark">
            @yield('registro')
        </body>
    </html>
    @yield('scripts')

resources/views/reporteFinal.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('bread-reporteFinal')
                        <div class="text-center">
                        </div><br>
                        @yield('reporteFinal')
                    </div>
                    @yield('footer')
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')

resources/views/reportes.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('form')
                    </div>
                    @yield('footer')
                </div>
            </div>
            @yield('top')
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        </body>
        <script>
            $(document).ready(function(){           
                var d = new Date();                                                
                var strDate =d.getDate()  + "/" + (d.getMonth()+1) + "/" + d.getFullYear();   
                $('#fechaini').show(strDate);                   
                $('#boton').hide();
                $("#fechaini").change(function(){
                    var fechai=new Date($('#fechaini').val());
                    var fechaf=new Date($('#fechafin').val());
                    if (fechai.getTime()>fechaf.getTime()){
                        $('#boton').hide();                        
                    }else{ 
                        $('#boton').show();                        
                    }
                });
                $("#fechafin").change(function(){
                    var fechai=new Date($('#fechaini').val());
                    var fechaf=new Date($('#fechafin').val());
                    if (fechai.getTime()>fechaf.getTime()){
                        $('#boton').hide();                    
                    }else{
                        $('#boton').show();
                    }                    
                });
                
                    
            });
        </script>
    </html>
    @yield('scripts')

resources/views/seguimiento.blade.php
@include('layouts.scripts')
@include('layouts.footer')
@include('layouts.breadcrumb')

<!DOCTYPE html>
    <html lang="en">
        <head>
            @include('layouts.head')
        </head>
        <body id="page-top">
            {{-- NAVBAR --}}
            @yield('navbar')
            @yield('logout')
            {{-- CONTENT --}}
            <div id="wrapper">
                @yield('sidebar')
                <div id="content-wrapper">
                    <div class="container-fluid">
                        @yield('bread-seguimiento')
                        @yield('progreso')<br>
                        @yield('tickets')
                    </div>
                    @yield('footer')
                </div>
            </div>
            @yield('top')
        </body>
    </html>
    @yield('scripts')