routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');
Route::resource('licencia_equipo','LicenciaEquipoController');
Route::get('licencia_equipo/create','LicenciaEquipoController@create')->name('licencia_equipo.create');
Route::get('licencia_equipo/numero/{id}','LicenciaEquipoController@numero')->name('licencia_equipo.numero');
Route::get('equipo/numero/{id}','EquipoController@numero')->name('equipo.numero');
 Route::resource('equipo','EquipoController');
 Route::get('equipo/create','EquipoController@create')->name('equipo.create');
 Route::get('equipo/show/{id}','EquipoController@show')->name('equipo.show');
Route::post('equipo/store/{id}','EquipoController@store')->name('equipo.store');
Route::get('index', function () {
    return redirect('equipo');
 });
 Route::get('licencia_equipo/show/{id}','LicenciaEquipoController@show')->name('licencia_equipo.show');
 Route::post('licencia_equipo/store/{id}','LicenciaEquipoController@store')->name('licencia_equipo.store');
 Route::get('csv', function(){
    $n= DB::table('equipo_licencia')
    ->select('licencias.nombre_programa','licencias.digitos','licencias.version','licencias.subversion','equipos.nserie_equipo','users.name','users.departamento')
     ->join('licencias','equipo_licencia.licencia_id','=','licencias.id')
     ->join('equipos','equipo_licencia.equipo_id','=','equipos.id')
     ->join('users','equipos.user_id','=','users.id')
     ->get();
     $filename = "licencias.csv";
     $handle = fopen($filename, 'w+');
     fputcsv($handle, array('nombre del programa', 'digitos','version','subversion','numero de serie del equipo','usuario','departamento'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->nombre_programa,$row->digitos,$row->version,$row->subversion,$row->nserie_equipo,$row->name,$row->departamento));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'licencias.csv', $headers);

 })->name('exportar');
 
//rutas para solicitud de mantenimiento
Route::resource('mantenimiento','MantenimientoController');
Route::get('mantenimiento/pdf/{id}','MantenimientoController@create_pdf')->name('mantenimiento.pdf');

//rutas para apoyo de correos
Route::resource('apoyo','ApoyoController');
Route::get('/refresh_captcha', 'ApoyoController@refreshCaptcha')->name('refresh');
Route::resource('correos','CorreoController');
Route::get('correos/destroy/{id}', 'CorreoController@destroy')->name('correos.destroy');
Route::get('correos/show/{id}', 'CorreoController@show')->name('correos.show');
Route::get('csvc', function(){
    $n= DB::table('apoyos')
    ->select('*')
    ->from('apoyos')
     ->get();
    
   $filename = "ApoyoCorreosCompleto.csv";
   $handle = fopen($filename, 'w+');
     fputcsv($handle, array('numero de control', 'carrera','apellido paterno','apellido materno','nombre','peticion','descripcion del problema'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->numerocontrol,$row->carrera,$row->apellidoPaterno,$row->apellidoMaterno,$row->nombre,$row->opcion,$row->descripcion));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'ApoyoCorreosCompleto.csv', $headers);

 })->name('exportarcompleta');



Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

resources/views/admin/agregaCategoria.blade.php
@extends('categoria')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')
@include('layouts.app')

@section('categoria-tabla')
<div id="listar"></div>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Agregar categoría
    </div>
    <div class="card-body">
        <div class="table-responsive">
                <script type="text/javascript" src="../../../public/js/jquery-3.4.1.min.js"></script>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

                <?php echo '<form action="categoria/store" method="post">' ?>
                @csrf
                <div class="modal-body center">
                    <div class="row form-group">
                        <div class="col-12">
                            <input type="text" name="id"  id="id" hidden="">
                            <label for="solicitante">Categoria:</p>
                        </div>
                        <div class="col-12">
                            <input type="text" class="form-control" name="categoria" id="categoria"  required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-12">
                            <label for="solicitante">Descripcion:</p>
                        </div>
                        <div class="col-12">
                            <textarea type="text" class="form-control" name="descripcion" id="descripcion" required=""></textarea>
                        </div>
                    </div>
                   
                </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </div>
        </form>
                  



</table>
</div>
</div>
<div class="card-footer small text-muted">Actualizado ayer a las 11:59 PM</div>
</div>
@endsection




@section('top')
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
@endsection

resources/views/admin/asignar_licencia.blade.php
@extends('equipos')
@include('layouts.navbar')
@include('layouts.sidebarAdmin') 
@section('solicitudes-tabla')
<div class="card mb-3">
<h5>Agregar Equipo del usuario: {{$user->name}}<br>
Departamento {{$user->departamento}}</h5>
{{-- <h5>Licencias Diponibles: </h5> --}}
<h5>Numero de serie del equipo (Activo)</h5>
<br>
<form style="margin-left:180px" class="col s12" method="post" action="{{ route('equipo.store',$user->id )}}">
 @csrf
             <div class="row form-group">
                        <div class="col-6">
                            <label for="nserie_equipo"> Equipo (Numero de serie activo): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="nserie_equipo" name="nserie_equipo" placeholder="Escribe el numero de serie del equipo:">
                            {{-- <a href="{{ url('/licencia_usuario/equipolicencia/'.$licenciasusuario->id)}}" class="btn btn-success ">Asignar licencias al equipo</a>  --}}
                        </div>
             </div>  
             
         <br> <div class="footer">
                {{-- <button type="submit" class="btn btn-primary" > Aceptar </button> --}}
                <button class="btn btn-primary" type="submit" onclick="return confirm('¿Guardar? Verifique antes que la información del equipo este correcta')">Aceptar </button>
            </div>
            
        </div>
         {{-- <a class="btn btn-warning" href="{{url('/licencia_usuario/create')}}" > Regresar</a> --}}
        </div>
         
 </form>
 
 </div>
@endsection

resources/views/admin/editarasignacion.blade.php
@extends('asignacioneditar')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')  
 @section('solicitudes-tabla')

                    <h5 class="modal-title text-center" id="exampleModalLabel"> EDITAR INFORMACIÓN </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ url('/equipo/'.$licenciasusuario->id)}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="modal-body">
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="nserie_equipo"> Equipo(Numero de serie activo): </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="nserie_equipo" name="nserie_equipo" value="{{$licenciasusuario->nserie_equipo}}">
                            </div>
                        </div>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                    </div>
                </form>
                {{-- <a class="btn btn-warning" href="{{url('/licencia_usuario/')}}" > Regresar</a> --}}
            </div>
             
        </div>
          
                               
                            
    </div>
    @endsection
 

resources/views/admin/editlicencia.blade.php
@extends('licenciaeditar')
 @include('layouts.navbar')
@include('layouts.sidebarAdmin')  
@section('solicitudes-tabla')

                    <h5 class="modal-title text-center" id="exampleModalLabel"> EDITAR INFORMACIÓN </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ url('/altalicencias/'.$licencias->id)}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="modal-body">
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="nombre_programa">Nombre del programa: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="nombre_programa" name="nombre_programa" value="{{$licencias->nombre_programa}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="digitos">Ultimos 5 digitos de la Licencia:</label>
                            </div>
                            <div class="col-9">
                                <input required required class="form-control" id="digitos" name="digitos" value="{{$licencias->digitos}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="version">Versión: </label>
                            </div>
                            <div class="col-9">
                                <input required class="form-control" id="version"  name="version" value="{{$licencias->version}}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-3">
                                <label for="subversion"> Subversión (Solo si aplica): </label>
                            </div>
                            <div class="col-9">
                                <input  class="form-control" id="subversion" name="subversion" value="{{$licencias->subversion}}">
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                        
                    </div>
                   
                </form>
                {{-- <div class="col-3">
                                <a class="btn btn-warning" href="{{url('/altalicencias/')}}" > Regresar</a>
                            </div> --}}
                
            </div>
            
        </div>
    </div>
   
    @endsection

resources/views/admin/editmantenimiento.blade.php
@extends('editmantenimiento')
@include('layouts.navbar')
@include('layouts.sidebarAdmin') 
@section('solicitudes-tabla')
<div class="card mb-3">
 <div class="card-header">
        <i class="fas fa-table"></i>
       Editar solicitud de mantenimiento
    </div>
    <div class="card-body">
 <div class="table-responsive">
 <form action="{{ url('/mantenimiento/'.$mantenimiento->id)}}" method="post" enctype="multipart/form-data" >
               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="form-group">
                    {{-- fecha --}}
                 <label for="fecha" name="fecha" id="fecha" > Fecha: </label>
                 <input  type="date" class="form-control" name="fecha" id="fecha" required  value="{{$mantenimiento->fecha}}">
                </div>  
  {{-- área--}}
         <label  > Área Solicitante : (Escribe el área solicitante o despliega las opciones (Departamentos))</label><br>
<input list="area" name="area" placeholder="Doble clic menú desplegable de opciones (Departamentos)" class="form-control" style="height: 50px; width: 460px;" value="{{$mantenimiento->area}}" required="">
<datalist id="area">
  <option value="Ciencias Económico - Administrativo">Ciencias Económico - Administrativo</option>
                  <option value="DEPI">DEPI</option>
                  <option value="Eléctrica">Eléctrica</option>
                  <option value="Gestión Empresarial">Gestión Empresarial</option>
                  <option value="Ingeniería Bioquimica">Ingeniería Bioquimica</option>
                  <option value="Ingeniería Industrial">Ingeniería Industrial</option>
                  <option value="Ingeniería en Materiales">Ingeniería en Materiales</option>
                  <option value="Ingeniería Mécanica">Ingeniería Mécanica</option>
                  <option value="Ingeniería Mecatrónica">Ingeniería Mecatrónica</option>
                  <option value="Posgrado de Eléctrica">Posgrado de Eléctrica</option>
                  <option value="Sistemas y Computación">Sistemas y Computación</option>
</datalist>
 {{-- Responsable del area--}}
 <label  > Responsable del Área: </label><br>
<input list="responsable" name="responsable" placeholder="Centro de cómputo o categoría" class="form-control" style="height: 50px;  width: 460px;" value="{{$mantenimiento->responsable}}" required="">
<datalist id="responsable">
  <option value="Centro de Cómputo">Centro de Cómputo</option>
</datalist>
 

{{-- Tipo de servicio--}}
  <label > Tipo de servicio </label><br>
  <div class="container">
  <div class="row">
    <div class="col">
      <label style="margin-left: 80px;" > Recursos Materiales y Servicios: </label><br>
                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Limpieza" @if(($mantenimiento->tiposervicio)=="Limpieza") checked @endif />
                     <label for = "tiposervicio">Limpieza</label>

                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Cerrajería"  @if(($mantenimiento->tiposervicio)=="Cerrajería") checked @endif/>
                     <label for = "tiposervicio">Cerrajería</label>
                  </p>

                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Evento"  @if(($mantenimiento->tiposervicio)=="Evento") checked @endif/>
                     <label for = "tiposervicio">Evento</label>
                  </p>
                <p>
                 <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Mobiliario" @if(($mantenimiento->tiposervicio)=="Mobiliario") checked @endif />
                     <label for = "tiposervicio">Mobiliario</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Otro"  @if(($mantenimiento->tiposervicio)=="Otro") checked @endif />
                     <label for = "tiposervicio">Otro</label>
                  </p>

    </div>
    <div class="col">
    <label style="margin-left: 80px;" > Centro de Cómputo: </label><br>
                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Hardware" @if(($mantenimiento->tiposervicio)=="Hardware") checked @endif />
                     <label for = "tiposervicio">Hardware</label>
                  </p>

                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Software"  @if(($mantenimiento->tiposervicio)=="Software" ) checked @endif/>
                     <label for = "tiposervicio">Software</label>
                  </p>
              
               <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Telefónia"  @if(($mantenimiento->tiposervicio)=="Telefónia") checked @endif/>
                     <label for = "tiposervicio">Telefónia</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Internet"  @if(($mantenimiento->tiposervicio)=="Internet") checked @endif/>
                     <label for = "tiposervicio">Internet</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Redes" @if(($mantenimiento->tiposervicio)=="Redes") checked @endif />
                     <label for = "tiposervicio">Redes</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Otro" @if(($mantenimiento->tiposervicio)== "Otro") checked @endif />
                     <label for = "tiposervicio">Otro</label>
                  </p>
                  
    </div>
  </div>

{{-- Descripción--}}
 <div class="row form-group">
                        <div style="margin-left: 30px;">
                            <label for="descripcion"> Descripción del servicio que solicita o falla a reparar: </label>
                        </div>
                         <br>
                        <div class="col-9" >
                            <textarea type="text" class="form-control" id="descripcion" name="descripcion" required="" style="height: 68px; width: 366px; margin-left: 30px;"> {{$mantenimiento->descripcion}}</textarea>
                        </div>
                    </div>

{{-- Trabajo o servicio realizado--}}
 <label for="serviciorealizado" style="margin-left: 30px;"> Trabajo o servicio realizado: </label>
 <div class="row form-group">
                        <br>
                        <div class="col-9">
                            <textarea type="text" class="form-control" id="serviciorealizado" name="serviciorealizado" required="" style="height: 68px; width: 366px; margin-left: 30px;" > {{$mantenimiento->serviciorealizado}}</textarea>
                        </div>
                    </div>


{{-- Material--}}
 <label  style="margin-left: 30px;" for="material"> Material Utilizado: </label>
 <div class="row form-group">
                      
                         <br>
                        <div class="col-9">
                            {{-- <input type="text" class="form-control" id="version" name="version" required=""> --}}
                            <textarea type="text" class="form-control" id="material" name="material" required=""style="height: 68px; width: 366px; margin-left: 30px;" > {{$mantenimiento->material}}</textarea>
                        </div>
                    </div>
{{-- Solicita--}}
<div class="row form-group">
                        <div class="col-3">
                            <label for="solicitante"> Solicita (Nombre): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="solicitante" name="solicitante" value="{{$mantenimiento->solicitante}}" required="">
                        </div>
                    </div>

{{-- Atendio--}}
  <div class="row form-group">
                        <div class="col-3">
                            <label for="realizador"> Atendió (Nombre): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="realizador" name="realizador" value="{{$mantenimiento->realizador}}" required="">
                        </div>
                    </div>
{{-- Vo.Bo--}}

                     <div class="row form-group">
                        <div class="col-3">
                            <label for="recibidor"> Vo.Bo (Nombre)</label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="recibidor" name="recibidor" value="{{$mantenimiento->recibidor}}" required="">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                        
                    </div>
                   
                </form>
               
      </div>
    </div>
</div>
@endsection

resources/views/admin/equiposlicencias.blade.php
@extends('licenciasasignacion')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')  
@section('solicitudes-tabla')
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Listado de licencias
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th> Usuario</th>
                         <th>Departamento</th>
                        <th> Equipo (Numero de serie activo)</th>
                        <th> Asignar licencias</th>
                        <th> Número de licencias</th>
                    </tr>
                </thead>
               <tbody>
               @foreach($licenciasUsuario as $licencia)
                   <tr>
                    <td>{{ $licencia->user->name}}</td>
                    <td>{{ $licencia->user->departamento}}</td>
                    <td>{{ $licencia->nserie_equipo}}</td>
               <td><a href="{{ url('/licencia_equipo/show/'.$licencia->id)}}" class="btn btn-success ">Asignar licencias</a>  </td>
                <td><a href="{{ url('/licencia_equipo/numero/'.$licencia->id)}}" class="btn btn-success ">Detalles</a> </td>
                   </tr>
               @endforeach
               </tbody> 
           </table>
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
 {{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
@endsection

resources/views/admin/licenciasasignacion.blade.php
@extends('equipos')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')  
 @section('solicitudes-tabla')

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
       Agregar Equipos
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th> Usuario</th>
                        <th> Departamento</th>
                        <th> Agregar Equipos</th>
                        {{-- <th> Número de Equipos-Detalles</th>  --}}
                    </tr>
                </thead>
               <tbody>
               @foreach($users as $user)
                   <tr>
                    <td>{{ $user->name}}</td>
                    <td>{{ $user->departamento}}</td>
                    <td><a href="{{ url('/equipo/show/'.$user->id)}}" class="btn btn-success ">Agregar Equipos</a>  </td>
                   {{-- <td><a href="{{ url('/equipo/numeroequipo/'.$user->id)}}" class="btn btn-success ">Detalles</a> </td>  --}}
                   </tr>
               @endforeach
               </tbody> 
           </table>
        
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
{{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
@endsection 

resources/views/admin/ticket.blade.php
@extends('ticket')
@include('layouts.navbar')
@include('layouts.sidebarAdmin')

@section('solicitud')
    <div class="text-center">
        <h1> NUEVO TICKET </h1>
    </div>
    <form method="POST" action="{{route('tickets.store')}}">
        {{csrf_field()}}
        <div class="form-group">
          <label for="exampleFormControlSelect1"> Equipo a Reportar: </label>
          <select class="form-control" id="selectEquipo" name="selectEquipo" onchange="" required >
            <option value="Teléfono"> Teléfono </option>
            <option value="Impresora"> Impresora </option>
            <option value="Laptop / PC"> Laptop / PC </option>
            <option value="Otro"> Otro </option>
          </select>
        </div>
        <div class="form-group">            
          <input type="text" placeholder="Otro" class="form-control" id="inputEquipo" name="inputEquipo" value=" " required hidden=""  />
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Tipo de Reporte: </label>
            <select class="form-control" id="selectTipoReporte" name="selectTipoReporte" onchange="" required>
                <option value="1"> Falla </option>
                <option value="3"> Solicitud </option>
                <option value="2"> Actividad </option>
                <option value="4"> Otro </option>
            </select>
        </div>
        <div class="form-group">            
          <input type="text" placeholder="Otro" class="form-control" id="inputtipoReporte" name="inputtipoReporte" value=" " required hidden="" />
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Categoria de reporte: </label>
            <select class="form-control" id="selectCategoria" name="selectCategoria"  onchange="" required>
            <?php
            foreach ($categorias as $categoria) {
                echo "<option value='".$categoria->id."'>".$categoria->categoriaReporte."</option>";
            }
            ?>
            </select>
        </div>
        
        
        <div class="form-group">
            <label for="exampleFormControlSelect1"> Nivel de Urgencia: </label>
            <select class="form-control" id="selectUrgencia" name="selectUrgencia"  onchange="otro()" required>
                <option value="4"> Bajo </option>
                <option value="3" selected > Medio </option>
                <option value="2"> Alto </option>
                <option value="1"> Urgente </option>
            </select>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1" id="labelUrgencia"> Explique la urgencia </label>
          <textarea class="form-control"  rows="3" name="textUrgencia" id="textUrgencia" required> </textarea>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1"> Ingrese los detalles del reporte </label>
          <textarea class="form-control" id="exampleFormControlTextarea1" name="detalles" rows="3" required></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary mb-2" style="width: 100%;"> Enviar </button>
        </div>
    </form>
@endsection

@section('top')
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
@endsection