routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');
Route::resource('licencia_equipo','LicenciaEquipoController');
Route::get('licencia_equipo/create','LicenciaEquipoController@create')->name('licencia_equipo.create');
Route::get('licencia_equipo/numero/{id}','LicenciaEquipoController@numero')->name('licencia_equipo.numero');
Route::get('equipo/numero/{id}','EquipoController@numero')->name('equipo.numero');
 Route::resource('equipo','EquipoController');
 Route::get('equipo/create','EquipoController@create')->name('equipo.create');
 Route::get('equipo/show/{id}','EquipoController@show')->name('equipo.show');
Route::post('equipo/store/{id}','EquipoController@store')->name('equipo.store');
Route::get('index', function () {
    return redirect('equipo');
 });
 Route::get('licencia_equipo/show/{id}','LicenciaEquipoController@show')->name('licencia_equipo.show');
 Route::post('licencia_equipo/store/{id}','LicenciaEquipoController@store')->name('licencia_equipo.store');
 Route::get('csv', function(){
    $n= DB::table('equipo_licencia')
    ->select('licencias.nombre_programa','licencias.digitos','licencias.version','licencias.subversion','equipos.nserie_equipo','users.name','users.departamento')
     ->join('licencias','equipo_licencia.licencia_id','=','licencias.id')
     ->join('equipos','equipo_licencia.equipo_id','=','equipos.id')
     ->join('users','equipos.user_id','=','users.id')
     ->get();
     $filename = "licencias.csv";
     $handle = fopen($filename, 'w+');
     fputcsv($handle, array('nombre del programa', 'digitos','version','subversion','numero de serie del equipo','usuario','departamento'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->nombre_programa,$row->digitos,$row->version,$row->subversion,$row->nserie_equipo,$row->name,$row->departamento));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'licencias.csv', $headers);

 })->name('exportar');
 
//rutas para solicitud de mantenimiento
Route::resource('mantenimiento','MantenimientoController');
Route::get('mantenimiento/pdf/{id}','MantenimientoController@create_pdf')->name('mantenimiento.pdf');

//rutas para apoyo de correos
Route::resource('apoyo','ApoyoController');
Route::get('/refresh_captcha', 'ApoyoController@refreshCaptcha')->name('refresh');
Route::resource('correos','CorreoController');
Route::get('correos/destroy/{id}', 'CorreoController@destroy')->name('correos.destroy');
Route::get('correos/show/{id}', 'CorreoController@show')->name('correos.show');
Route::get('csvc', function(){
    $n= DB::table('apoyos')
    ->select('*')
    ->from('apoyos')
     ->get();
    
   $filename = "ApoyoCorreosCompleto.csv";
   $handle = fopen($filename, 'w+');
     fputcsv($handle, array('numero de control', 'carrera','apellido paterno','apellido materno','nombre','peticion','descripcion del problema'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->numerocontrol,$row->carrera,$row->apellidoPaterno,$row->apellidoMaterno,$row->nombre,$row->opcion,$row->descripcion));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'ApoyoCorreosCompleto.csv', $headers);

 })->name('exportarcompleta');



Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Login </title>

  <!-- Custom fonts for this template-->
  <link href={{asset('vendor/fontawesome-free/css/all.min.css')}} rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{{ asset('css/sb-admin.css')}}" rel="stylesheet">
 </head>

<body class="bg-dark">
    <div id="app">
        <main class="py-4">
          
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/footer.blade.php
@include('layouts.app')

@section('footer')
    <footer class="sticky-footer">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
            <span> Ticket Manager 2019 </span>
            </div>
        </div>
    </footer>
@endsection

resources/views/layouts/head.blade.php
@include('layouts.app')

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title> TICKET MANAGER </title>

<!-- Custom fonts for this template-->
<link href="{{ URL::asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<!-- Page level plugin CSS-->
<link href="{{ URL::asset('vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="{{ URL::asset('css/sb-admin.css') }}" rel="stylesheet" type="text/css">

resources/views/layouts/logadmin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title> Login </title>

  <!-- Custom fonts for this template-->
  <link href="{{ asset('vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{{ asset('css/sb-admin.css')}}" rel="stylesheet">
 
</head>

<body class="bg-dark">
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html"> TICKET MANAGER </a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Notificaciones</a>
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Eliminar notificaciones</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Mensajes</a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Eliminar mensajes</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Ajustes de cuenta</a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Salir</a>
        </div>
      </li>
    </ul>

  </nav>
    <div id="app">
    
        <main class="py-4">
          
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/login.blade.php
@extends('layouts.app')
@extends('login')

@section('login')
<div class="container" style="margin-top: 100px;">
    <h1 class="text-center" style="color: white;"> TICKET MANAGER </h1>
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="POST" action="{{ route('login') }}">
          @csrf
          <div class="form-group">
              <div class="form-label-group">
		      <input type="email" id="inputEmail" class="form-control" placeholder="Correo electronico" name="email" value="{{ old('email') }}" required >
              <label for="inputEmail">Correo electronico</label>
            </div>
          </div>
          <div class="form-group">
            <div class="form-label-group">
              <input id="inputPassword" type="password" class="form-control" placeholder="Contraseña" name="password" required>
              <label for="inputPassword">Contraseña</label>
            </div>
          </div>
          <!-- <div class="form-group">
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me">
                Remember Password
              </label>
            </div>
          </div> -->
          <button type="submit" class="btn btn-primary btn-block">
            {{ __('Login') }}
          </button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{{url('/registro')}}"> Solicitar acceso </a>
          <a class="d-block small mt-3" href="{{url('/apoyo')}}"> Apoyo Correo Electronico</a>
        </div>
      </div>
    </div>
@endsection

resources/views/layouts/logusr.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{{asset('css/materialize.min.css')}}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <meta charset="utf-8">
      <script src="https://kit.fontawesome.com/75924fa61f.js"></script>
      <script type="text/javascript" src="{{asset('/jQuery/jquery-3.4.1.min.js')}}"></script>
      <script type="text/javascript" src="{{asset('/js/javascript.js')}}"></script>
      <script type="text/javascript" src="{{asset('/js/materialize.min.js')}}"></script>
      <script type="text/javascript" src="{{asset('/js/materialize.js')}}"></script>
</head>
<body>
    <div id="app">
        <section>
    <ul id="dropdown1" class="dropdown-content">
      <li ><h6 class="center">Ordenar por:</h6></li>
      <li class="divider"></li>
  <li><a href="/Laravel/blogWeb/public/post/OrderbyCateg">Categorias</a></li>
  <li><a href="/Laravel/blogWeb/public/post/OrderbyRecen">Recientes</a></li>
  <li><a href="/Laravel/blogWeb/public/post/OrderbyViews">Mas vistos</a></li>
  <li class="divider"></li>
  <li><a href="/Laravel/blogWeb/public/post/showAll">Ver todos</a></li>
</ul>
  </section>
    <div class="navbar-fixed">
  <nav class="" style="background-color: #00293C">
    <div class="container">
    <div class="nav-wrapper ">
      <a href="/Laravel/blogWeb/public/home" class="brand-logo mobile">Blog</a>
        
        
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="hoverable"><a href="/Laravel/blogWeb/public/home">Home</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Publicaciones<i class="material-icons right">arrow_drop_down</i></a></li>
        <li class="hoverable"><a href="/Laravel/blogWeb/public/users/showAll">Miembros</a></li>
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="/Laravel/blogWeb/public/user/profile/{{Auth::user()->id}}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>
        
        <li class="hoverable"><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Log out</a></li>
                

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
                </form>
                
        
        <!--<li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                            -->
      </ul>
    </div>
  </div>
</nav>
</div>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<footer class="page-footer" style="background-color: #00293C;">
  <br><br><br><br>
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h2 class="white-text">Programando la vida.</h2>
                <p class="grey-text text-lighten-4">“No te preocupes si no funciona bien. Si todo lo que hizo lo hiciera, estarías sin trabajo.” </p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Siguenos en nuestras redes sociales</h5>
                <div class="col l4 offset-l2 s12 m6">
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Linkedin</a></li>
                </ul>
              </div>
              <div class="col l4 offset-l2 s12 m6">
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fab fa-facebook-square fa-2x"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fab fa-twitter-square fa-2x"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fab fa-instagram fa-2x"></i></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!"><i class="fab fa-linkedin fa-2x"></i></a></li>
                </ul>
              </div>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            </div>
          </div>
</footer>
</html>

resources/views/layouts/navbar.blade.php
@include('layouts.app')

@section('navbar')
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="{{ url('index') }}"> TICKET MANAGER </a>

        <!-- BOTÓN SIDEBAR -->
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- USUARIO -->
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <li style="color: white; margin-top: 7px;"> {{ Auth::user()->apellidoP." ".Auth::user()->apellidoM." ".Auth::user()->name }} </li>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-lg"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    
                    <div class="dropdown-divider"></div>
                    <!-- <a class="dropdown-item" href="#"> Cerrar Sesión </a> -->
                    <a class="dropdown-item" href="{{ route('logout') }}"onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        {{ __('Cerrar Sesión') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                </div>
            </li>
        </ul>
    </nav>
@endsection

@section('logout')
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/navbarUsuario.blade.php
@include('layouts.app')

@section('navbar')
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="{{ url('index') }}"> TICKET MANAGER </a>

        <!-- BOTÓN SIDEBAR -->
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- USUARIO -->
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <li style="color: white; margin-top: 7px;"> {{ Auth::user()->apellidoP." ".Auth::user()->apellidoM." ".Auth::user()->name }} </li>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-lg"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    
                    <div class="dropdown-divider"></div>
                    <!-- <a class="dropdown-item" href="#"> Cerrar Sesión </a> -->
                    <a class="dropdown-item" href="{{ route('logout') }}"onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        {{ __('Cerrar Sesión') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                </div>
            </li>
        </ul>
    </nav>
@endsection

@section('logout')
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/sidebarAdmin.blade.php
@include('layouts.app')
@section('sidebar')
    <ul class="sidebar navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/tickets') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span> Inicio </span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" href="{{ url('/solicitudes-tickets') }}">
                <i class="fas fa-fw fa-sticky-note"></i>
                <span> Solicitudes de Tickets </span>
            </a>
            
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/solicitudes-usuarios') }}">
            <i class="fas fa-fw fa-user-circle"></i>
            <span> Solicitudes de Acceso </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/usuarios') }}">
            <i class="fas fa-fw fa-users"></i>
            <span> Usuarios </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/categorias') }}">
            <i class="fas fa-fw fa-table"></i>
            <span>Categorías </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/reportes') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Reportes </span></a>
        </li>
        <div class="dropdown-divider"></div>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('tickets.create') }}">
            <i class="fas fa-fw fa-list"></i>
            <span> Generar Ticket </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/seguimiento') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Seguimiento </span></a>
        </li>
        {{-- solicitud de mantenimiento --}}
         <div class="dropdown-divider"></div>
          <li class="nav-item">
            <a class="nav-link" href="{{ url('/mantenimiento ') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Solicitud de mantenimiento </span></a>
        </li>
         {{-- Apoyo Correos--}}
         <div class="dropdown-divider"></div>
          <li class="nav-item">
            <a class="nav-link" href="{{ url('/correos') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Apoyo Correos </span></a>
        </li>
        {{-- licencias --}}
         <div class="dropdown-divider"></div>
         <li class="nav-item">
            <a class="nav-link" href="{{ url('/altalicencias ') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Alta de Licencias </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('equipo.create') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Alta Equipos </span></a>
        </li>
         <li class="nav-item">
            <a class="nav-link" href="{{ url('/licencia_equipo') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Asignación de Licencias </span></a>
        </li>
         <li class="nav-item">
            <a class="nav-link" href="{{ url('/equipo') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Consulta de licencias </span></a>
        </li> 
        
    </ul>
@endsection

resources/views/layouts/sidebarEditar.blade.php
@include('layouts.app')
@section('sidebar')
    <ul class="sidebar navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/tickets') }}">
            <i class="fas fa-fw fa-list"></i>
            <span> Regresar </span></a>
        </li>
    </ul>
@endsection

resources/views/layouts/sidebarNoAprob.blade.php
@section('sidebar')
    <ul class="sidebar navbar-nav">
        
    </ul>
@endsection

resources/views/layouts/sidebarUser.blade.php
@include('layouts.app')
@section('sidebar')
    <ul class="sidebar navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('tickets.create') }}">
            <i class="fas fa-fw fa-list"></i>
            <span> Generar Ticket </span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url('/seguimiento') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Seguimiento </span></a>
        </li>
    </ul>
@endsection