routes/web.php
<?php

Route::get('/', function () {
    // return view('admin.index');
    return view ('layouts.login');
});
Route::post('/filtrar', 'TicketController@filtrar');
Route::get('/index', 'userController@index');
// Route::get('/index', function () {
//     return view('admin.index');
// });
Route::get('tickets/rejected/{id}', 'TicketController@rejected');

// Route::get('/usuarios', function () {
//     return view('admin.usuarios');
// });

Route::get('/nuevo-ticket', function () {
    return view('usuario.ticket');
});

//Sin autenticación
Route::get('seguimiento', 'TicketController@seguimientoTicket');
Route::get('esperaAprob', 'userController@esperaAprob');

Route::get('/perfil', function () {
    return view('layouts.perfil');
});

Route::get('/login', function () {
    return view('layouts.login');
});

Route::get('/registro', function () {
    return redirect('register');
});
//Agregadas para solicitud de acceso 3_12  
	Route::get('/solicitudes-usuarios', 'userController@solicitudesUsuarios');
	Route::post('/filtrar-solicitud', 'userController@filtrarSolicitud');
	Route::post('user/update', 'userController@updateAcceso');	
//Agregadas para el crud de categorias 4_12
    Route::get('/categorias', 'categoriaController@index');
    Route::post('categoria/delete', 'categoriaController@delete');
    Route::post('categoria/update', 'categoriaController@update');
    Route::post('categoria/store', 'categoriaController@store');
    Route::get('/agregarCategoria', function () {
        return view('admin.agregaCategoria');
    });
    Route::post('categoria/findCategoria', 'categoriaController@show');
//Agregadas para generar reportes
    Route::get('reportes', 'TicketController@reportesTickets');
    Route::post('reporteCreate', 'TicketController@crearReporte');
    Route::get('reporteSolicitud/{id}', 'TicketController@crearReporteSolicitud');
// Agregadas para la solicitud
    Route::get('/solicitudes-tickets', 'TicketController@solicitudes2');
    Route::post('/solicitudes-tickets/aceptarTicket', 'TicketController@aceptarTicket');

// rutas para el reporte de solicitud
    Route::get('/reporte', 'TicketController@reporteFinal');
    Route::post('/reporte/update', 'TicketController@reporteUpdate');

//rutas para las licencias
Route::resource('altalicencias','LicenciaController');
Route::resource('licencia_equipo','LicenciaEquipoController');
Route::get('licencia_equipo/create','LicenciaEquipoController@create')->name('licencia_equipo.create');
Route::get('licencia_equipo/numero/{id}','LicenciaEquipoController@numero')->name('licencia_equipo.numero');
Route::get('equipo/numero/{id}','EquipoController@numero')->name('equipo.numero');
 Route::resource('equipo','EquipoController');
 Route::get('equipo/create','EquipoController@create')->name('equipo.create');
 Route::get('equipo/show/{id}','EquipoController@show')->name('equipo.show');
Route::post('equipo/store/{id}','EquipoController@store')->name('equipo.store');
Route::get('index', function () {
    return redirect('equipo');
 });
 Route::get('licencia_equipo/show/{id}','LicenciaEquipoController@show')->name('licencia_equipo.show');
 Route::post('licencia_equipo/store/{id}','LicenciaEquipoController@store')->name('licencia_equipo.store');
 Route::get('csv', function(){
    $n= DB::table('equipo_licencia')
    ->select('licencias.nombre_programa','licencias.digitos','licencias.version','licencias.subversion','equipos.nserie_equipo','users.name','users.departamento')
     ->join('licencias','equipo_licencia.licencia_id','=','licencias.id')
     ->join('equipos','equipo_licencia.equipo_id','=','equipos.id')
     ->join('users','equipos.user_id','=','users.id')
     ->get();
     $filename = "licencias.csv";
     $handle = fopen($filename, 'w+');
     fputcsv($handle, array('nombre del programa', 'digitos','version','subversion','numero de serie del equipo','usuario','departamento'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->nombre_programa,$row->digitos,$row->version,$row->subversion,$row->nserie_equipo,$row->name,$row->departamento));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'licencias.csv', $headers);

 })->name('exportar');
 
//rutas para solicitud de mantenimiento
Route::resource('mantenimiento','MantenimientoController');
Route::get('mantenimiento/pdf/{id}','MantenimientoController@create_pdf')->name('mantenimiento.pdf');

//rutas para apoyo de correos
Route::resource('apoyo','ApoyoController');
Route::get('/refresh_captcha', 'ApoyoController@refreshCaptcha')->name('refresh');
Route::resource('correos','CorreoController');
Route::get('correos/destroy/{id}', 'CorreoController@destroy')->name('correos.destroy');
Route::get('correos/show/{id}', 'CorreoController@show')->name('correos.show');
Route::get('csvc', function(){
    $n= DB::table('apoyos')
    ->select('*')
    ->from('apoyos')
     ->get();
    
   $filename = "ApoyoCorreosCompleto.csv";
   $handle = fopen($filename, 'w+');
     fputcsv($handle, array('numero de control', 'carrera','apellido paterno','apellido materno','nombre','peticion','descripcion del problema'));
     foreach($n as $row) {
         fputcsv($handle, array( $row->numerocontrol,$row->carrera,$row->apellidoPaterno,$row->apellidoMaterno,$row->nombre,$row->opcion,$row->descripcion));
     }
     fclose($handle);
 
     $headers = array(
         'Content-Type' => 'text/csv',
     );
 
  return Response::download($filename, 'ApoyoCorreosCompleto.csv', $headers);

 })->name('exportarcompleta');



Route::post('tickets/update', 'TicketController@update');
Route::resource('tickets', 'TicketController');
Route::resource('usuarios', 'userController'); 
Route::get('/usuarios', 'userController@index');
Route::get('/home', function(){
	return redirect('tickets');
});
Auth::routes();

resources/views/agente/asignaestatus.blade.php
@extends('correo')
@include('layouts.navbar')
@include('layouts.sidebarAgente')  
@section('solicitudes-tabla')
<div class="card mb-3">
 <div class="card-header">
        <i class="fas fa-table"></i>
      Asignar estatus <br>
      Nombre: {{$datos->nombre}} {{$datos->apellidoPaterno}} {{$datos->apellidoMaterno}}<br>
      Numero Control: {{$datos->numerocontrol}}<br>
      Carrera: {{$datos->carrera}}
    </div>
    <div class="card-body">
 <div class="table-responsive">
  <form action="{{ url('/apoyo/'.$datos->id)}}" method="post" enctype="multipart/form-data" > 

               {{csrf_field()}}
                {{method_field('PATCH')}}
                    <div class="form-group">
                  
       
          {{-- Opciones--}}
              <div class="form-group">
                        <div class="form-label-group">
                          <div class="form-group">
                  <select class="form-control" id="estatus" name="estatus"  required >
                    <option value="Recibido" @if(($datos->estatus)=="Recibido")  selected @endif>Recibido</option>
                    <option value="Atendido" @if(($datos->estatus)=="Atendido")  selected @endif>Atendido</option>
                    <option value="Cancelado"@if(($datos->estatus)=="Cancelado")  selected @endif>Cancelado</option>
                  </select>
                   
                </div>
          </div>
        </div>
    

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary"> Aceptar </button>
                        
                    </div>
                   
                </form>
               
      </div>
    </div>
</div>
@endsection

resources/views/agente/datosNovalidados.blade.php
@extends('correo')
@include('layouts.navbar')
@include('layouts.sidebarAgente')  
@section('solicitudes-tabla')
 
   <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">     
<div class="card mb-3">

    <div class="card-header">
        <i class="fas fa-table"></i>
        Datos de peticiones (No validadas)
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                    <th> Validar</th>
                        <th> Fotografia (acercar cursor para zoom)</th>
                         <th> Estatus</th>
                        <th> Cambiar estatus </th>
                        <th> Numero de Control</th>
                        <th> Carrera</th>
                        <th> Nombre</th>
                        <th> Apellido Paterno</th>
                         <th>Apellido Materno</th> 
                        <th> Peticion</th>
                        <th> Descripción</th>
                        <th> Email</th>
                        <th> Numero de atencion</th>
                        <th> Fecha de Creación</th>
                        <th>Opciones </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

              <form method="POST" action="{{route('correos.store')}}">
                    @csrf 
                  
                  @foreach($datosNoValidados as $datosNoValidado )
                  <tr>

                   <td>
                   <input type="checkbox"  name="validados[]" id="{{$datosNoValidado}}" value="{{ $datosNoValidado->numerocontrol}},{{ $datosNoValidado->carrera}},{{ $datosNoValidado->apellidoPaterno}},{{ $datosNoValidado->apellidoMaterno}},{{ $datosNoValidado->nombre}},{{ $datosNoValidado->opcion}},{{ $datosNoValidado->descripcion}}"> 
                
                    </td> 

                     <td>
                     <img src="{{ asset('storage').'/'.$datosNoValidado->foto}}" style="width:60%;cursor:zoom-in" onclick="onClick(this)">
                     <div id="modal01" class="w3-modal" onclick="this.style.display='none'">
                     <span class="w3-button w3-hover-red w3-xlarge w3-display-topright">&times;</span>
                     <div class="w3-modal-content w3-animate-zoom">
  <img class="w3-modal-content" id="img01"style="width:100%">
  </div>
</div> 
                       </td> 
                        <td>{{ $datosNoValidado->estatus}}</td> 
                     <td> <a class=" btn btn-success" href="{{route('correos.show',$datosNoValidado->id)}}" class="secondary-content"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-clockwise" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
  <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
</svg></a></a>
                   </td>
                    <td>{{ $datosNoValidado->numerocontrol}}</td>
                    <td>{{ $datosNoValidado->carrera}}</td>
                    <td>{{ $datosNoValidado->nombre}}</td>
                    <td>{{ $datosNoValidado->apellidoPaterno}}</td>
                    <td>{{ $datosNoValidado->apellidoMaterno}}</td>
                    <td>{{ $datosNoValidado->opcion}}</td>
                    <td>{{ $datosNoValidado->descripcion}}</td>
                    <td>{{ $datosNoValidado->email}}</td>
                    <td>{{ $datosNoValidado->order_nr}}</td> 
                    <td>{{ $datosNoValidado->created_at}}</td> 
                    <td> 
                     <a class="btn btn-warning" href="{{url('/correos/'.$datosNoValidado->id.'/edit')}}" class="secondary-content"><i class="fa fa-edit"></i></a></a>
                       {{-- <a href="{{route('correos.destroy',$datosNoValidado->id)}}" class="btn btn-danger"onclick="return confirm('¿Borrar?');"><i class="fa fa-trash"></i></a>  --}}
                    </td>
       
                   </tr>
                     @endforeach
   </tbody> 
     
      </table>   
           <button type="submit" class="btn btn-info" >Exportar a CSV</button>    
             </form>     
              <br>  <br><a  href="{{ route('exportarcompleta') }}"  class="btn btn btn-secondary" style="width: 300px">Exportar a CSV tabla completa</a>        
           {{-- <img src=" {{ asset('storage').'/'.$datosNoValidado->foto}}" onmouseover="this.width=1000;this.heigh=1000;"onmouseout="this.width=50;this.heigh=50;"alt="" width="50">  --}}
                    {{-- <img src=" {{ asset('storage').'/'.$datosNoValidado->foto}}" alt="" width="400"> --}}
              
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
   
{{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
<script>
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
}
</script>

   

@endsection

resources/views/agente/detalles.blade.php
@extends('licenciasconsulta')
@include('layouts.navbar')
@include('layouts.sidebarAgente')  
@section('solicitudes-tabla')
<div class="card mb-3">
     <div class="row form-group">
                         <div class="col-12">
                            <label for="nserie_equipo">Usuario: {{$equipo->user->name }}</label> 
                        </div> 
                        <div class="col-12">
                            <label for="nserie_equipo">Departamento: {{$equipo->user->departamento }}</label> 
                        </div> 
                        <div class="col-12">
                            <label for="nserie_equipo">Equipo (Numero de serie activo): {{$equipo->nserie_equipo}}</label> 
                        </div>
                        <div class="col-6">
                            <label for="nserie_equipo">Número de licencias asignadas: {{ $e}}</label> 
                        </div>
             </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
{{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
@endsection

resources/views/agente/licencias.blade.php
@extends('licenciass')
@include('layouts.navbar')
@include('layouts.sidebarAgente')  
@section('solicitudes-tabla')
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Listado de licencias
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>

                        <th> Nombre del programa </th>
                        <th> Licencia Digitos</th>
                        <th> Versión del Programa</th>
                        <th> Subversión </th>
                        {{-- <th> Opciones </th>
                        <th></th> --}}
                    </tr>
                </thead>
               <tbody>
               @foreach($licencias as $licencia)
                   <tr>
                    <td>{{ $licencia ->nombre_programa }}</td>
                    <td>{{ $licencia ->digitos}}</td>
                    <td>{{ $licencia->version }}</td>
                    <td>{{ $licencia->subversion }}</td>
                    {{-- <td> <a class="btn btn-warning" href="{{url('/altalicencias/'.$licencia->id.'/edit')}}" class="secondary-content"><i class="fa fa-edit"></i></a></a></td>
                    <td>
                         <form method="post" action="{{url('/altalicencias/'.$licencia->id)}}">
                               {{csrf_field()}}
                               {{method_field('DELETE')}}

                               <button   class="btn btn-danger" type="submit" onclick="return confirm('¿Borrar?');"><i class="fa fa-trash"></i></button>                 
                           </form>
                    </td> --}}
                   </tr>
               @endforeach
               </tbody>
           </table>
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
 {{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
@endsection



@section('modalregistro')
<div class="modal fade" id="modalregistro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title text-center" id="exampleModalLabel"> AGREGAR LICENCIA </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>


            <form action="{{route('altalicencias.store')}}" method="post" >
                {{csrf_field()}}
                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="nombre_programa"> Nombre del programa: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="nombre_programa" name="nombre_programa" required="">
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-3">
                            <label for="digitos"> Ultimos 5 digitos de la Licencia: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="digitos" name="digitos" required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="version"> Versión: </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="version" name="version" required="">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-3">
                            <label for="subversion"> Subversión (Solo si aplica): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="subversion" name="subversion" >
                        </div>
                    </div>
             
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </div>
        </form>
    </div>
    
</div>
</div>
@endsection

resources/views/agente/mantenimientos.blade.php
@extends('mantenimiento')
@include('layouts.navbar')
@include('layouts.sidebarAgente')  
@section('solicitudes-tabla')

<div class="card mb-3">

    <div class="card-header">
        <i class="fas fa-table"></i>
        Mantenimientos
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      {{-- <th> Nombre del programa </th>
                        <th> Licencia Digitos</th> --}}
                         <th> Descargar PDF</th>
                        <th> Folio</th>
                        <th> Fecha</th>
                        <th> Área Solicitante</th>
                        <th> Responsable del Área</th>
                        <th> Tipo de servicio</th>
                         <th>Descripción del servicio o falla</th> 
                        <th> Trabajo o servicio realizado</th>
                        <th> Material Utilizado</th>
                        <th>Solicitante</th>
                         <th> Atendio</th>
                           {{-- <th> Opciones</th> --}}
                    </tr>
                </thead>
                <tbody>
               @foreach($mantenimientos as $mantenimiento )
                   <tr>
                   <td> <a href="{{ url('/mantenimiento/pdf/'.$mantenimiento->id) }}"class="btn btn-success "><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 5a.5.5 0 0 0-1 0v4.793L5.354 7.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 9.793V5z"/>
</svg> </td>
                    <td>{{ $mantenimiento->id}}</td>
                    <td>{{ $mantenimiento->fecha}}</td>
                    <td>{{ $mantenimiento->area}}</td>
                    <td>{{ $mantenimiento->responsable}}</td>
                    <td>{{ $mantenimiento->tiposervicio}}</td>
                    <td>{{ $mantenimiento->descripcion}}</td>
                    <td>{{ $mantenimiento->serviciorealizado}}</td>
                    <td>{{ $mantenimiento->material}}</td>
                    <td>{{ $mantenimiento->solicitante}}</td>
                    <td>{{ $mantenimiento->realizador}}</td>
                    {{-- <td>
                    <form method="post" action="{{url('/mantenimiento/'.$mantenimiento->id)}}">
                               {{csrf_field()}}
                               {{method_field('DELETE')}}

                               <button   class="btn btn-danger" type="submit" onclick="return confirm('¿Borrar?');"><i class="fa fa-trash"></i></button>                 
                           </form>
                    <a class="btn btn-warning" href="{{url('/mantenimiento/'.$mantenimiento->id.'/edit')}}" class="secondary-content"><i class="fa fa-edit"></i></a></a>
                    </td> --}}
                {{-- <td><a href="{{ url('/licencia_equipo/show/'.$licencia->id)}}" class="btn btn-success ">Asignar licencias</a>  </td> --}}
                   </tr>
               @endforeach

               </tbody> 
           </table>
             {{-- <a  href="{{ route('exportar') }}"  class="btn btn-info" style="width: 200px">Exportar a CSV</a>  --}}
              {{-- href="/tick/public/csv" --}}
       </div>
   </div>
   <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
{{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
@endsection

@section('modalregistro')
<div class="modal fade" id="modalregistro" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title text-center" id="exampleModalLabel"> Solicitud de mantenimiento </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>


            <form action="{{route('mantenimiento.store')}}" method="post" >
                {{csrf_field()}}
                <div class="modal-body">
                   
                 <div class="form-group">
                 <label for="fecha" name="fecha" id="fecha" > Fecha: </label>
                 <input  type="date" class="form-control" name="fecha" id="fecha" required >
                </div>  
                

                      <label > Área Solicitante : (Escribe el área solicitante o despliega las opciones (Departamentos))</label><br>
<input list="area" name="area" placeholder="Doble clic menú desplegable de opciones (Departamentos)" class="form-control" style="height: 50px; width: 460px;" required>
<datalist id="area">
  <option value="Ciencias Económico - Administrativo">Ciencias Económico - Administrativo</option>
                  <option value="DEPI">DEPI</option>
                  <option value="Eléctrica">Eléctrica</option>
                  <option value="Gestión Empresarial">Gestión Empresarial</option>
                  <option value="Ingeniería Bioquimica">Ingeniería Bioquimica</option>
                  <option value="Ingeniería Industrial">Ingeniería Industrial</option>
                  <option value="Ingeniería en Materiales">Ingeniería en Materiales</option>
                  <option value="Ingeniería Mécanica">Ingeniería Mécanica</option>
                  <option value="Ingeniería Mecatrónica">Ingeniería Mecatrónica</option>
                  <option value="Posgrado de Eléctrica">Posgrado de Eléctrica</option>
                  <option value="Sistemas y Computación">Sistemas y Computación</option>
</datalist>

   
<br>
 <label  > Responsable del Área: </label><br>
<input list="responsable" name="responsable" placeholder="Centro de cómputo o categoría" class="form-control" style="height: 50px;" required="">
<datalist id="responsable">
  <option value="Centro de Cómputo">Centro de Cómputo</option>
</datalist>
<br>
  
 
  

<label > Tipo de servicio </label><br>
<label style="margin-left: 80px;" > Recursos Materiales y Servicios: </label><br>
 <div class = "row">
               <div class = "input-field col s3">
                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Limpieza"  />
                     <label for = "tiposervicio">Limpieza</label>
                  </p>
                  
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Cerrajería"  />
                     <label for = "tiposervicio">Cerrajería</label>
                  </p>
              
                <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Evento"  />
                     <label for = "tiposervicio">Evento</label>
                  </p>
                <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Mobiliario"  />
                     <label for = "tiposervicio">Mobiliario</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Otro"  />
                     <label for = "tiposervicio">Otro</label>
                  </p>
             </div>
       </div>
       <label style="margin-left: 80px;" > Centro de Cómputo</label><br>
 <div class = "row">
               <div class = "input-field col s3">
                   <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Hardware"  />
                     <label for = "tiposervicio">Hardware</label>
                  </p>
                  
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Software"  />
                     <label for = "tiposervicio">Software</label>
                  </p>
              
                <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Telefónia"  />
                     <label for = "tiposervicio">Telefónia</label>
                  </p>
                <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Internet"  />
                     <label for = "tiposervicio">Internet</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Redes"  />
                     <label for = "tiposervicio">Redes</label>
                  </p>
                  <p>
                     <input id = "tiposervicio" type = "radio" name = "tiposervicio"
                        value = "Otro"  />
                     <label for = "tiposervicio">Otro</label>
                  </p>
             </div>
       </div>
                    <div class="row form-group">
                        <div style="margin-left: 30px;">
                            <label for="descripcion"> Descripción del servicio que solicita o falla a reparar: </label>
                        </div>
                        <div class="col-9">
                            {{-- <input type="text" class="form-control" id="version" name="version" required=""> --}}
                            <textarea type="text" class="form-control" id="descripcion" name="descripcion" required=""style="height: 68px; width: 366px; margin-left: 30px;"></textarea>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div style="margin-left: 30px;">
                            <label for="serviciorealizado"> Trabajo o servicio realizado: </label>
                        </div>
                        <div class="col-9">
                            {{-- <input type="text" class="form-control" id="version" name="version" required=""> --}}
                            <textarea type="text" class="form-control" id="serviciorealizado" name="serviciorealizado" required=""style="height: 68px; width: 366px; margin-left: 30px;" ></textarea>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div style="margin-left: 30px;">
                            <label for="material"> Material Utilizado: </label>
                        </div>
                        <div class="col-9">
                            {{-- <input type="text" class="form-control" id="version" name="version" required=""> --}}
                            <textarea type="text" class="form-control" id="material" name="material" required=""style="height: 68px; width: 366px; margin-left: 30px;" ></textarea>
                        </div>
                    </div>


                    <div class="row form-group">
                        <div class="col-3">
                            <label for="solicitante"> Solicita (Nombre): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="solicitante" name="solicitante" required>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-3">
                            <label for="realizador"> Atendió (Nombre): </label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="realizador" name="realizador"  required>
                        </div>
                    </div>

                     <div class="row form-group">
                        <div class="col-3">
                            <label for="recibidor"> Vo.Bo (Nombre)</label>
                        </div>
                        <div class="col-9">
                            <input class="form-control" id="recibidor" name="recibidor" required>
                        </div>
                    </div>
             
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> Cancelar </button>
                <button type="submit" class="btn btn-primary"> Aceptar </button>
            </div>
        </form>
    </div>
    {{-- <a class="btn btn-warning" href="{{url('/tickets/')}}" > Regresar</a> --}}
</div>
</div>
@endsection